CREATE TABLE ai_tools (
    tool_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_name VARCHAR2(100) NOT NULL,
    description CLOB,
    category_id NUMBER,
    developer VARCHAR2(100),
    release_date DATE,
    website_url VARCHAR2(200),
    pricing_info VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);


CREATE TABLE tool_features (
    feature_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_id NUMBER REFERENCES ai_tools(tool_id),
    feature_name VARCHAR2(100) NOT NULL,
    feature_description CLOB
);

CREATE TABLE reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_id NUMBER REFERENCES ai_tools(tool_id),
    user_id NUMBER,
    rating NUMBER(1) CHECK (rating BETWEEN 1 AND 5),
    comments CLOB,
    review_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(50) UNIQUE,
    category_description CLOB
);

CREATE TABLE user_saved_tools (
    save_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    tool_id NUMBER REFERENCES ai_tools(tool_id),
    saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tool_tags (
    tag_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_id NUMBER REFERENCES ai_tools(tool_id),
    tag_name VARCHAR2(50)
);

CREATE TABLE feedback (
    feedback_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    message CLOB,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);